<<<<<<< HEAD
title: Jonas' GitHub
description: About Jonas & Repository List
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
=======
theme: jekyll-theme-slate
>>>>>>> 68dd01266ce2baa781beef6c3c551caa2a3ae952
